// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKowtWI1S9z8trqP8O5tenuAIfpglMO5g',
    appId: '1:196396931491:web:43f770d5a87d85df432216',
    messagingSenderId: '196396931491',
    projectId: 'flutterfirebaseauthentic-f231b',
    authDomain: 'flutterfirebaseauthentic-f231b.firebaseapp.com',
    storageBucket: 'flutterfirebaseauthentic-f231b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARskBc8LnGlBgmALJIzlqQjQyBM9Huers',
    appId: '1:196396931491:android:0514a04b94178b73432216',
    messagingSenderId: '196396931491',
    projectId: 'flutterfirebaseauthentic-f231b',
    storageBucket: 'flutterfirebaseauthentic-f231b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKZaz0RhbubOf17kuieW4pjt-C4QxQMjY',
    appId: '1:196396931491:ios:2ec211a2ed650a4e432216',
    messagingSenderId: '196396931491',
    projectId: 'flutterfirebaseauthentic-f231b',
    storageBucket: 'flutterfirebaseauthentic-f231b.appspot.com',
    iosClientId: '196396931491-2527d3rd8mb6rdbq8a320uvdknb2c4iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKZaz0RhbubOf17kuieW4pjt-C4QxQMjY',
    appId: '1:196396931491:ios:df3b90cbeb787bae432216',
    messagingSenderId: '196396931491',
    projectId: 'flutterfirebaseauthentic-f231b',
    storageBucket: 'flutterfirebaseauthentic-f231b.appspot.com',
    iosClientId: '196396931491-0n9v19u6dpdja02f1sjc07v3v8q77ugq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth.RunnerTests',
  );
}
